version: '3.8'

services:
  pllm-plus:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UNAME: ${USER:-appuser}
        UID:   ${UID:-1000}
        GID:   ${GID:-1000}

    image: pllm-plus:latest
    container_name: pllm-plus-test

    networks:
      - pllm-network

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ../../hard-gists:/gists:rw
      - ../../pllm_results:/gists/pllm_results:ro
      - ../../pyego-results:/gists/pyego-results:ro
      - ../../readpy-results:/gists/readpy-results:ro
    
    working_dir: /app

    stdin_open: true
    tty: true

    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

networks:
  pllm-network:
    driver: bridge
